"""
    LVAxes(longitudinal, lateral, anteroposterior, apex, base_center)

Anatomical frame of a left ventricle.

* `longitudinal` is the unit long axis, oriented from the apex towards the base.
* `lateral` and `anteroposterior` complete a right-handed orthonormal frame, i.e.
  `anteroposterior = longitudinal × lateral`.
* `apex` and `base_center` pin the long axis in space. A direction alone does not
  determine the axis of a mesh that is not centered at the origin, and every
  cylindrical coordinate built on top of it needs the line, not just the slope.

Use [`compute_lv_axes`](@ref) to derive the frame from a mesh.

!!! note
    `lateral` is the dominant direction of the short-axis cross section. On a
    ventricle with a circular cross section -- every idealized mesh generated by
    [`generate_ideal_lv_mesh`](@ref) -- that cross section is isotropic, so
    `lateral` is determined by discretization noise rather than by anatomy. Pass
    an explicit reference direction wherever the azimuthal origin matters.
"""
struct LVAxes{T}
    longitudinal::Vec{3, T}
    lateral::Vec{3, T}
    anteroposterior::Vec{3, T}
    apex::Vec{3, T}
    base_center::Vec{3, T}
end

function LVAxes(
    longitudinal::Vec{3, T},
    lateral::Vec{3, T},
    apex::Vec{3, T},
    base_center::Vec{3, T},
) where {T}
    l = longitudinal / norm(longitudinal)
    r = lateral - (lateral ⋅ l) * l
    nr = norm(r)
    nr < sqrt(eps(T)) &&
        throw(ArgumentError("LVAxes: `lateral` must not be collinear with `longitudinal`."))
    return LVAxes(l, r / nr, l × (r / nr), apex, base_center)
end

function Base.show(io::IO, ::MIME"text/plain", axes::LVAxes)
    println(io, "LVAxes:")
    println(io, "  longitudinal:    ", axes.longitudinal)
    println(io, "  lateral:         ", axes.lateral)
    println(io, "  anteroposterior: ", axes.anteroposterior)
    println(io, "  apex:            ", axes.apex)
    print(io, "  base_center:     ", axes.base_center)
end

_node_coordinates(grid::AbstractGrid) = [get_node_coordinate(node) for node in getnodes(grid)]

function _facetset_node_ids(grid::AbstractGrid, facetset)
    ids = OrderedSet{Int}()
    for (cellidx, local_facet) in facetset
        for nodeid in Ferrite.facets(getcells(grid, cellidx))[local_facet]
            push!(ids, nodeid)
        end
    end
    return collect(ids)
end

"""
Total least squares plane through `points`, returned as `(centroid, unit normal)`.
The normal is the eigenvector of the covariance with the smallest eigenvalue, i.e.
the direction in which the points spread the least. Its sign is arbitrary here and
fixed by the caller.
"""
function _fit_plane(points::AbstractVector{Vec{3, T}}) where {T}
    centroid = sum(points) / length(points)
    cov = zeros(T, 3, 3)
    for x in points
        d = x - centroid
        for i = 1:3, j = 1:3
            cov[i, j] += d[i] * d[j]
        end
    end
    eig = eigen(Symmetric(cov))
    k = argmin(eig.values)
    return centroid, Vec{3, T}((eig.vectors[1, k], eig.vectors[2, k], eig.vectors[3, k]))
end

"""
Dominant direction of `points` after projecting out `longitudinal`. Falls back to a
cardinal direction when the projected cloud is degenerate.
"""
function _principal_short_axis(
    points::AbstractVector{Vec{3, T}},
    centroid::Vec{3, T},
    longitudinal::Vec{3, T},
) where {T}
    cov = zeros(T, 3, 3)
    for x in points
        d = x - centroid
        d -= (d ⋅ longitudinal) * longitudinal
        for i = 1:3, j = 1:3
            cov[i, j] += d[i] * d[j]
        end
    end
    eig = eigen(Symmetric(cov))
    k = argmax(eig.values)
    candidate = Vec{3, T}((eig.vectors[1, k], eig.vectors[2, k], eig.vectors[3, k]))
    candidate -= (candidate ⋅ longitudinal) * longitudinal
    if norm(candidate) < sqrt(eps(T))
        candidate = _any_orthogonal(longitudinal)
    end
    return candidate / norm(candidate)
end

"Some unit vector orthogonal to `v`."
function _any_orthogonal(v::Vec{3, T}) where {T}
    fallback = abs(v[1]) < T(0.9) ? Vec{3, T}((1, 0, 0)) : Vec{3, T}((0, 1, 0))
    w = fallback - (fallback ⋅ v) * v
    return w / norm(w)
end

function _lv_axes(
    coords::AbstractVector{Vec{3, T}},
    base_center::Vec{3, T},
    apex::Vec{3, T},
) where {T}
    longitudinal = base_center - apex
    norm(longitudinal) < sqrt(eps(T)) &&
        error("compute_lv_axes: apex and base center coincide, the long axis is undefined.")
    longitudinal /= norm(longitudinal)
    centroid = sum(coords) / length(coords)
    lateral = _principal_short_axis(coords, centroid, longitudinal)
    return LVAxes(longitudinal, lateral, apex, base_center)
end

"""
    compute_lv_axes(mesh; base = "Base", apex = nothing)
    compute_lv_axes(mesh, plane_point::Vec{3}, plane_normal::Vec{3})

Derive the long axis and the anatomical frame of a left ventricle from its geometry.

The first form reads the basal plane off the `base` facetset: `base_center` is the
centroid of its nodes and the basal normal is the total-least-squares plane normal,
oriented away from the bulk of the mesh. The apex is taken from the `apex` nodeset
when one is given, and otherwise is the node lying farthest below that plane.

The second form is for meshes that carry no basal annotation: the plane is supplied
directly, the apex is again the node farthest below it, and `base_center` is the
centroid of the nodes within the top 5% of the basal-distance range. `plane_normal`
points out of the ventricle at the base, i.e. from the apex towards the base -- the
same orientation that selects the basal facets when the plane is used to cut a mesh.

In both cases the short-axis frame comes from a principal axis analysis of the nodes
projected onto the plane orthogonal to the long axis -- see the note in [`LVAxes`](@ref)
about its degeneracy on rotationally symmetric geometries.
"""
function compute_lv_axes(
    grid::AbstractGrid{3};
    base::String = "Base",
    apex::Union{Nothing, String} = nothing,
)
    coords = _node_coordinates(grid)
    isempty(coords) && error("compute_lv_axes: the mesh has no nodes.")

    base_nodes = _facetset_node_ids(grid, getfacetset(grid, base))
    isempty(base_nodes) && error("compute_lv_axes: facetset '$base' is empty.")
    base_center, normal = _fit_plane(coords[base_nodes])

    # Orient the basal normal away from the myocardium, so that "below the plane"
    # means "towards the apex".
    centroid = sum(coords) / length(coords)
    (base_center - centroid) ⋅ normal < 0 && (normal = -normal)

    apex_point = if apex === nothing
        coords[argmin([(x - base_center) ⋅ normal for x in coords])]
    else
        apex_nodes = collect(getnodeset(grid, apex))
        isempty(apex_nodes) && error("compute_lv_axes: nodeset '$apex' is empty.")
        sum(coords[apex_nodes]) / length(apex_nodes)
    end

    return _lv_axes(coords, base_center, apex_point)
end

function compute_lv_axes(
    grid::AbstractGrid{3},
    plane_point::Vec{3, T},
    plane_normal::Vec{3, T},
) where {T}
    coords = _node_coordinates(grid)
    isempty(coords) && error("compute_lv_axes: the mesh has no nodes.")

    normal = plane_normal / norm(plane_normal)
    signed = [(x - plane_point) ⋅ normal for x in coords]
    apex_point = coords[argmin(signed)]

    # Everything within the top 5% of the basal-distance range counts as "the base".
    band = max((maximum(signed) - minimum(signed)) * T(0.05), T(1.0e-3))
    cutoff = maximum(signed) - band
    basal = [coords[i] for i in eachindex(coords) if signed[i] >= cutoff]
    base_center = isempty(basal) ? plane_point : sum(basal) / length(basal)

    return _lv_axes(coords, base_center, apex_point)
end
